# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

theMagnetic = "There's only one question that really needs to be asked of 69 Love Songs: is it a brilliant masterpiece or merely very, very good? The title alone is enough to send music geeks the world over into a foamy-mouthed, epileptic frenzy. 69 songs equals 3 CDs equals nearly three solid hours of new Magnetic Fields material-- think of it! That's more than some notable bands released in their entire existence. Add that to the fact that the Magnetic Fields actually followed through with their concept without turning it into the indie-pop equivalent of Lou Reed's Metal Machine Music.

You see, I have this theory that music critics are suckers for novelty, and there isn't much in this world that's more novel than 69 Love Songs. It borders on being a prop in a Mark Leyner story-- it's hyperreal and excessive, yet perfectly plausible when you consider how weird reality is. Because of this, the album never feels like a ponderous, pretentious artistic statement (unlike most multi-CD releases). Stephin Merritt and company sound like they approached this ridiculously ambitious project with the most casual of airs, idly plucking melody after divine melody out of the air like low-hanging fruit from a tree. It's how pop music should sound, really: so natural and feather-light that you never notice the amount of effort that went into it.

Therein lies the paradox of 69 Love Songs-- it's such a basic style of music that it's easy to dismiss it as 'just pop music.' Of course, that's what it is, so should it really deserve such high praise? Should it rank among the best albums of the 1990s? Or is it too bizarre to be considered culturally important? I mean, Abbey Road is a pretty weird album, too. Then again, Abbey Road isn't three hours long.

Regardless, Stephin Merritt has proven himself as an exceptional songwriter, making quantum leaps in quality as well as quantity on 69 Love Songs. This incarnation of the band doesn't feature much of the densely layered, burbling electro-pop that they're best known for; in its stead are sparser, more acoustic songs that sound as if they're being played on actual instruments by a group of actual musicians (as opposed to Merritt himself playing mad scientist with effects racks and overdubs). It may initially seem like this stylistic decision came due to budget restrictions-- if you're recording that many songs, you can't blow too much money on any one track. But it's probably more likely that Merritt finally realized the limits of tinny synths and drum machines."

petSounds = "May 16, 1966 – After a year’s worth of toiling and committing every single second of tape to his perfectionism, Brian Wilson’s magnum opus Pet Sounds was unveiled to mixed reactions. In America, it sparked complaints from those who expected more fun-in-the-sun/hot rod hits or simplistic love songs with a cookie cutter boy/girl element that The Beach Boys had perfected with classics such as ”Don’t Worry Baby” and ”Surfer Girl”. Capitol, the band’s label, hardly promoted the album based on the excuse that the album would sell based on the band’s popularity alone. Pet Sounds debuted at 106, peaked at 10, and practically underperformed in every single way in the States. On the other side of the pond, Britain lauded the album, sending it straight to the second spot on the charts. Several musicians and the press heaped praise upon the Boys’ latest album and hailed it as revolutionary.

Fifty years on, the claims that Britain’s music press made were long confirmed to be correct. To call it astounding, incredible, game-changing, innovative, all of that hyperbolic mumbo jumbo, is tired. Yet, it’s spot on in every way. Before Pet Sounds hit the scene decades ago, pop music had been heavily focused on selling singles. Even The Beach Boys were relatively a single-oriented group, their albums being the vehicle for said hits with some filler added on to move units. The story of how Wilson heard the reconfigured Rubber Soul is infamous in itself – in a moment of inspiration, Wilson runs to his wife, Marilyn and declares he’ll create the greatest album ever made. And with The Wrecking Crew at his disposal, Wilson set out to do just that. Over the spring of 1966, Wilson painstakingly led strenuous sessions laying down the backing tracks to several songs that had their beginnings as early as 1964 (“I’m Waiting for the Day”), while intending on having the complex vocal arrangements overdubbed by the absent Boys, who were on tour at the time of the initial recordings. Fast forward through their return, the group in-fighting that followed (in which the infamous “don’t fuck with the formula” story took root) and the gradual acceptance of Wilson’s compositions, and Pet Sounds as we know it was complete.

From the playful opening strains of ”Wouldn’t It Be Nice”, the change in direction is evident, yet subtle. Whereas the arrangement of the song is upbeat and perky, the lyrical subject of two young lovers who wish to be together, yet are restricted by their age is something that wasn’t new to the band’s repertoire (”I’m So Young” comes to mind) and isn’t exactly controversial today, but stirred up a bit of negative reactions upon its release in the more conservative parts of America. The reaction it got, however, was minor in comparison to ”God Only Knows”. In some parts of America, several listeners were outraged by the use of ‘God’ in a pop song, even getting it banned from the radio for its “blasphemous” lyrics. Aside from the controversy of those two songs, the lyrical content within Pet Sounds, like the musical arrangements, were ambitious and complex. Described by Beach Boy Mike Love to be “Brian’s ego music”, the themes leaned heavily on self-doubt, love, faith and alienation – all of which perfectly paralleled with Wilson’s feelings at the time.

The lyricism at some points, are heartbreaking ('Could I ever find in you again/things that made me love you so much then'), depressing ('Each time things start to happen again/I think I got something good goin' for myself/but what goes wrong?''), and at some points, devoid of hope (the tag for 'I Just Wasn't Made For These Times'; Wilson's tormented sentiments of a lost love in 'Caroline, No'). In terms of musicianship, Pet Sounds was ground-breaking. On several songs, such as ”That’s Not Me”, ”I Know There’s An Answer” and ”Caroline, No”, a pattern of gradually introducing more percussion is prominent, allowing the arrangements more room to breathe, as well as give more emphasis on the band’s vocals. On other songs, like the standout ”I Just Wasn’t Made For These Times”, the theremin is an alien element in the composition, perfectly portraying Wilson’s growing depression and alienation from society; or on ”Don’t Talk (Put Your Head On My Shoulder)”’s organ-dominated sound that showcased Wilson’s desperate vocal about a deteriorating romance in the absence of not only other session musicians, but the other Beach Boys."

abbeyRoad = "The 1960s were a big decade for rock music, and sprawled its presence among the world like a madman. Every high pitched voiced adolescent girl started whoring themselves out to new extremes, just to meet the bands they worshiped with paper posters on the walls of their suburban home bedrooms. Not one band was as popular among the pop-culture crowd as the Beatles, an English quartet from Liverpool, writing catchy songs about simplistic ideas, and scoring big with the world. In fact, so big, that no one has ever sold more albums than the four of them. They have remained the number one selling music artist of all time, through the present day, only slightly challenged by Led Zeppelin. And their release entitled Abbey Road just helped them further to gain that title. By now, I'm sure you all have heard the ludicrous rumors of Beatles bass player/songwriter/singer, Paul McCartney dying in a car accident early on, and being replaced with a look-alike. I'm more than sure that these rumors are just a creative myth, but there is some speculating evidence of that on Abbey Road. In addition to the previous backward tracking incidents on The White Album and Magical Mystery Tour, Abbey Road's cover shows Paul as walking in front of a car, as well as the only member without shoes. It may be just some dumb myth, but it is a bit spooky, and even if it's false, that is one very well thought out story, and some odd coincidences.

As you read the intro to my review, most likely, you carefully examined the definition of the word 'euphoria' and you probably thought 'How the hell does this word pertain to a Beatles album?'' Well, listening to the Beatles' Abbey Road is a euphoric feeling. Not one where you are being overly fanboyish, but the feeling of being well relaxed and at ease while listening to the noise which takes up seventeen slots on a round compact disc. But how is noise euphoric? Because John Lennon, George Harrison and Paul McCartney thought up vague, abstract, innocent, and simple ideas and turned them into bombastic, catchy, and intense songs. This seventeen-track work of art is an hour's worth of brilliant songwriting, and a masterpiece in and of itself. Ranging from little pop numbers that just exceed the ninety-second mark, into seven minute blues progressions, Abbey Road has been acclaimed as one of the Beatles' finest records to date, and I would probably agree with that phrase, minus the word
'Beatles'."

howItFeels = "Sunny Day Real estate was originally formed in 1992 amid the Seattle rock scene, and consisted of three members. Dan Hoerner played guitar and sang, Nate Mendel played bass, and William Goldsmith was the drummer. This set-up didn't last very long however as they soon added what would be the defining member of Sunny Day Real Estate, Jeremy Enigk, on vocals.

The band was very enigmatic and shy at the outset, only releasing one picture, and only conducting one interview in the 2 years leading up to their debut release Diary. In addition, the band never played live with all four members present.

In 1994, the group released Diary to much critical acclaim. This was the same year that Enigk became a born again Christian. In 1995, perhaps due to Enigk's newfound religion, the band broke up for the first time. Just before the breakup, however, Sunny Day Real Estate released their follow-up album (an album that is usually refered to as 'The Pink Album') LP2.

After the breakup, Goldsmith and Mendel became members of the band Foo Fighters, and Hoerner quit the music business altogether. A year after the breakup, Enigk returned with a solo acoustic record entitled The Return of the Frog Queen which he recorded with a 21 piece orchestra.

Two long years passed, the fan-base for Sunny Day Real Estate was actually growing despite the fact that they had disbanded, and fans eagerly bought up their first two albums. Then in 1997 the band reformed minus bassist Nate Mendel who was replaced with Jeff Palmer. The next year, the band would release the defining record of the 1990's, How It Feels to be Something On. They began touring again, and recorded a live album simply entitled Live in 1999.

In 2000, the band tried an album once again with The Rising Tide. The album was the first not on the Sub Pop label, and had a stronger prog-rock feel to it, as well as a softer tone throughout. The album was again hailed by critics however, the new record label's (Time Bomb) deal with Arista fell through. This made promotion of the record and touring almost impossible. In addition they had problems with managers, and in 2001 they announced that they were officially disbanded again."


#users
User.create(username: "Gabe", password: "123")

#Artists
Artist.create(name: "The Beach Boys", genre: "Pop Rock")
Artist.create(name: "The Magnetic Fields", genre: "Indie Rock")
Artist.create(name: "The Beathles", genre: "Pop Rock")
Artist.create(name: "Sunny Day Real Estate", genre: "Emo")

#Albums
Album.create(title: "Pet Sounds", img: "https://img.discogs.com/nCZN9cX7QoIxxctd2hh_psdmVw8=/fit-in/300x300/filters:strip_icc():format(jpeg):mode_rgb():quality(40)/discogs-images/R-4068511-1505195322-7754.jpeg.jpg", artist_id: Artist.first.id)
Album.create(title: "69 Love Songs", img: "https://upload.wikimedia.org/wikipedia/en/0/00/The_Magnetic_Fields_-_69_Love_Songs.jpg",  artist_id: Artist.second.id)
Album.create(title: "Abbey Road", img: "https://www.udiscovermusic.com/wp-content/uploads/2017/09/The-Beatles-Abbey-Road-Album-cover-web-optimised-820-820x600.jpg",  artist_id: Artist.third.id)
Album.create(title: "	How It Feels To Be Something On", artist_id: Artist.fourth.id, img: "https://images-na.ssl-images-amazon.com/images/I/717fQnFjC0L._SY355_.jpg")

#Reviews
Review.create(user_id: User.first.id, album_id: Album.first.id, rating: 8, review: petSounds, title: "Pet Sounds", artist: "The Beach Boys", img: "https://img.discogs.com/nCZN9cX7QoIxxctd2hh_psdmVw8=/fit-in/300x300/filters:strip_icc():format(jpeg):mode_rgb():quality(40)/discogs-images/R-4068511-1505195322-7754.jpeg.jpg", release_date: 1966 )
Review.create(user_id: User.first.id, album_id: Album.second.id, rating: 9, review: theMagnetic, title: "69 Love Songs", artist: "The Magnetic Fields", img: "https://upload.wikimedia.org/wikipedia/en/0/00/The_Magnetic_Fields_-_69_Love_Songs.jpg", release_date: 1998)
Review.create(user_id: User.first.id, album_id: Album.third.id, rating: 8, review: abbeyRoad, title: "Abbey Road", artist: "The Beatles", img: "https://www.udiscovermusic.com/wp-content/uploads/2017/09/The-Beatles-Abbey-Road-Album-cover-web-optimised-820-820x600.jpg", release_date: 2015)
Review.create(user_id: User.first.id, album_id: Album.fourth.id, rating: 8.3, review: howItFeels, title: "How It feels To Be On Something", artist: "Sunny Day Real Estate", img: "https://images-na.ssl-images-amazon.com/images/I/717fQnFjC0L._SY355_.jpg", release_date: 1998)

#comments
Comment.create(review_id: Review.first.id, user_id: User.first.id, comment: "First comment.", username: "Gabe")
